title: Minji Kim
subtitle: (김민지, @minjikim)
face: /assets/img/minjungkim.jpeg
#cv: https://drive.google.com/file/d/1DuI0Hul1Un-4AemKeqcZ9rYBJHxw163N/view?usp=sharing
cv: /assets/cv.pdf
description: AI Scientist at LG AI Research
location: Seoul, Korea
email: minjung.kim AT lgresearch.ai
homepage: https://minnjung.github.io
#twitter:
github: https://github.com/minnjung
linkedin: https://www.linkedin.com/in/minjung-kim-45148722a/
google_analytics: UA-146496389-1
theme: jekyll-theme-minimal
google_scholar: https://scholar.google.com/citations?user=nSwyFAMAAAAJ&hl=en
semantic_scholar: https://www.semanticscholar.org/author/Minjung-Kim/2109022768

plugins:
  - jekyll-seo-tag
